version: 2
updates:
  - package-ecosystem: "npm" # or any other ecosystem like "pip", "rubygems", etc.
    directory: "/" # location of your dependency files
    schedule:
      interval: "daily" # check for updates daily
  - package-ecosystem: "pip" # Python dependencies
    directory: "/" # location of your Python requirements file
    schedule:
      interval: "weekly" # check for updates weekly
